# Arrays
Numpy is a python library that allows to manipulate arrays. An array in programming is a sequence of contiguous cells in memory that can store elements of the same type. With respect to lists, in which elements are not contiguous, they allow a fast access to the elements when the array is scanned in order.
I can also define multidimensional arrays. For example, assume that I want to create a 3 dimensional array __v__ with shape (2,3,4). The shape of an array tells me the number of elements for each dimension of the array. Let us analyze what does it mean with the previous example:

__v__ has two elements in the first dimension, 3 elements in the second dimension and 4 elements in the fourth dimension meaning that each element of __v__, `v[i]` is another array with two dimensions, and each element of the second array, `v[i,j]` is another array of 4 elements.

The picture shows how the array is stored in memory:
<p align=center>
<img src=../imgs/02_md_array.png width=50%>
</p>


## Indexing

In [1]:
import numpy as np

In [2]:
# initialize a new array and fill it with ones
a = np.ones(shape=(2,3,4),dtype=np.int32)
a.shape

(2, 3, 4)

In [3]:
# i can also initialize an array from a Python list
v = np.asarray([
            [[111,112,113,114],[121,122,123,124],[131,132,133,134]],
            [[211,212,213,214],[221,222,223,224],[231,232,233,234]]],dtype=np.int32)
print((v.shape,v.dtype))
v

((2, 3, 4), dtype('int32'))


array([[[111, 112, 113, 114],
        [121, 122, 123, 124],
        [131, 132, 133, 134]],

       [[211, 212, 213, 214],
        [221, 222, 223, 224],
        [231, 232, 233, 234]]], dtype=int32)

In [4]:
# you can access the elements of an array through indexes, for example if i want
# to access the element in the first position in the first dimension, in the third
# position in the second dimension and in the fourth position in the third dimension
# i can write (remember that indexes start from zero)
v[0,2,3]

134

In [5]:
# if I only specify the first indices i get the multidimensional array addressed
# by that index (see the figure above)
v[1]

array([[211, 212, 213, 214],
       [221, 222, 223, 224],
       [231, 232, 233, 234]], dtype=int32)

In [6]:
# now assume I want to get all the elements where the index in the second dimension is 2.
# To do this I need to use the slice notation, I can index a dimension either using an index
# or using a slice, i.e by specifying start:stop:step, where step is optional. If I do not 
# specify the start and stop the default values are the first and last index in the dimension
v[:,2,:]


array([[131, 132, 133, 134],
       [231, 232, 233, 234]], dtype=int32)

In [7]:
# Now I want all the elements with an odd position in the second dimension and even position in the
# fourth dimension
v[:,1::2,::2]

array([[[121, 123]],

       [[221, 223]]], dtype=int32)

## Operations with arrays
In numpy I can make operations between arrays with the same shape. The operation is then applied elementwise

In [8]:
a = np.asarray([[1,2,3],[4,5,6]])
b = np.asarray([[1,1,1],[2,2,2]])

In [9]:
a + b

array([[2, 3, 4],
       [6, 7, 8]])

Numpy also implements the matrix product (rows by columns). It can be called explicitly with `np.matmul` or with 
the operator `@`. Note that the matrix product works if the two matrix have compatible shapes (the number of columns
 of the first is equal to the number of rows of the second).
$$
\begin{pmatrix}
a_{11} & a_{12} & a_{13} \\
a_{21} & a_{22} & a_{23}
\end{pmatrix}
\begin{pmatrix}
b_1 \\
b_2 \\
b_3
\end{pmatrix} = 
\begin{pmatrix}
a_{11}b_1 + a_{12}b_2 + a_{13}b_3 \\
a_{21}b_1 + a_{22}b_2 + a_{23}b_3
\end{pmatrix}
$$

In [10]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
b = np.asarray([1,2,3])
a @ b

array([14, 32])

## Broadcasting
What if the operands have different shapes? In some special cases we can still make operations between arrays with different shapes using a mechanism that is called Broadcasting.